[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytbv"
version = "0.1.0"
dependencies = [
    "packaging",
    "cocotb>=2.0.0",
    "pyuvm"
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false
